networks:
  development:
    external: true
    name: $DOCKER_NETWORK_NAME

services:
  postgresql:
    profiles:
      - infrastructure
    image: 'postgres:15.2'
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./infrastructure/data/postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '8081:5432'
    networks:
      - development

  traefik:
    profiles:
      - infrastructure
    image: 'traefik:v3.6.12'
    ports:
      - 80:80
      - 8080:8080
      - 50051:50051 # grpc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.grpc.address=:50051"
      - "--entrypoints.http.address=:80"
      - "--serversTransport.insecureSkipVerify=true"
    networks:
      - development

  card:
    profiles:
      - dev
    build:
      context: .
      target: development
    volumes:
      - ./card:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.card-grpc.loadbalancer.server.port=50051"
      - "traefik.http.services.card-grpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.routers.card-grpc.rule=Host(`card.remember_it.docker`)"
      - "traefik.http.routers.card-grpc.entrypoints=grpc"
    command: air -c /app/cmd/grpc_server/.air.toml
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - development

  telegram-bot:
    profiles:
      - dev
    build:
      context: .
      target: development
    volumes:
      - ./telegram-bot:/app
    command: air -c /app/cmd/bot/.air.toml
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - development

  telegram-miniapp:
    profiles:
      - dev
    build:
      context: .
      target: development
    volumes:
      - ./telegram-bot:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.miniapp-http.loadbalancer.server.port=8080"
      - "traefik.http.routers.miniapp-http.rule=Host(`miniapp.remember_it.docker`)"
      - "traefik.http.routers.miniapp-http.entrypoints=http"
    command: air -c /app/cmd/miniapp/.air.toml
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - development
