networks:
  development:
    external: true
    name: $DOCKER_NETWORK_NAME

services:
  card:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grpc.loadbalancer.server.port=50051"
      - "traefik.http.services.grpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.routers.grpc.rule=Host(`card.sm2.docker`)"
      - "traefik.http.routers.grpc.entrypoints=grpc"
    command: air -c /app/card/.air.toml
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - development

  telegram-bot:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: air -c /app/telegram-bot/.air.toml
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - development
