root = "/app"
tmp_dir = "/tmp"

[build]
bin = "/tmp/build"
args_bin=["--env=/app/.env"]
cmd = "go build -mod=vendor -o /tmp/build /app/cmd/miniapp/main.go"
delay = 1000
exclude_dir = ["vendor"]
exclude_regex = ["_test.go"]
log = "build-errors.log"
stop_on_error = true

[misc]
clean_on_exit = true