networks:
  development:
    external: true
    name: $DOCKER_NETWORK_NAME

services:
  postgresql:
    image: 'postgres:15.2'
    restart: always
    networks:
      development:
        aliases:
          - postgresql.$DOCKER_DOMAIN_NAME
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '8054:5432'

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 3000:3000
    environment:
      HTTP_PORT: 3000
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      development:
        aliases:
          - reverse_proxy.$DOCKER_DOMAIN_NAME
